services:
  siamdb:
    image: postgres
    volumes:
      - ./siam-backend/migrations:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data 
    ports:
      - '5434:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dani12345
      POSTGRES_DB: siam-bd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d siam-bd" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./siam-backend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - siamdb

  frontend:
    build:
      context: .
      dockerfile: ./siam-frontend/Dockerfile
    restart: always
    ports:
      - 4200:4200
    env_file:
      - .env
    depends_on:
      - backend
